services:
  - cassandra

language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  # pypy versions
  - "pypy"
  - "pypy3"
  - "pypy-5.3.1"
env:
  - CASSANDRA_DRIVER_VERSION=2.6.0
  - CASSANDRA_DRIVER_VERSION=2.7.2
  - CASSANDRA_DRIVER_VERSION=3.0.0
  - CASSANDRA_DRIVER_VERSION=3.1.1
  - CASSANDRA_DRIVER_VERSION=3.2.2
  - CASSANDRA_DRIVER_VERSION=3.3.0
  - CASSANDRA_DRIVER_VERSION=3.4.1
  - CASSANDRA_DRIVER_VERSION=3.5.0
  - CASSANDRA_DRIVER_VERSION=3.6.0
  - CASSANDRA_DRIVER_VERSION=3.7.1
matrix:
  exclude:
  - python: "pypy3"
    env: CASSANDRA_DRIVER_VERSION=2.6.0
install:
  - pip install -q cassandra-driver==$CASSANDRA_DRIVER_VERSION
  - pip install -q flask
  - python setup.py -q install

script: py.test
